# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: checkbashisms
    name: Check for bashisms in /bin/sh scripts
    entry: ./tests/Scripts/3rdparty/checkbashisms.pl
    language: script
    files: '.*\.sh'

  - id: autogen-docs
    name: Check that generated documentation is up-to-date
    entry: ./scripts/autogen-docs
    language: script

    pass_filenames: false
  - id: clang-format
    name: Run clang-format on code
    entry: ./scripts/run-clang-format
    args: ["--pre-commit-hook"]
    files: ^(hilti|spicy|zeek)/.*\.(c|h|C|H|cpp|hpp|cc|hh|c\+\+|h\+\+|cxx|hxx)$
    language: script

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
    exclude: '^tests/Baseline'
  - id: end-of-file-fixer
    exclude: '^tests/Baseline|^doc/autogen'
  - id: check-yaml
  - id: check-added-large-files

exclude: /3rdparty/|doc/.*examples/|/Baseline/|(\.svg$)|(\.dat$)
