# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: checkbashisms
    name: check for bashisms in /bin/sh scripts
    entry: ./tests/Scripts/3rdparty/checkbashisms.pl
    language: script
    files: '.*\.sh'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
    exclude: '^tests/Baseline'
  - id: end-of-file-fixer
    exclude: '^tests/Baseline|^doc/autogen'
  - id: check-yaml
  - id: check-added-large-files

exclude: /3rdparty/|doc/.*examples/|/Baseline/|(\.svg$)|(\.dat$)
